// <auto-generated />
using System;
using Csharp.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Csharp.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251026170533_AddFuncionarioSyncTable")]
    partial class AddFuncionarioSyncTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Csharp.Api.Entities.Beacon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<short>("Ativo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("BeaconId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<DateTime?>("UltimaVezVisto")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("UltimaZonaDetectada")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.HasIndex("BeaconId")
                        .IsUnique();

                    b.ToTable("Beacons");
                });

            modelBuilder.Entity("Csharp.Api.Entities.Funcionario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("CARGO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("FOTO_URL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<Guid>("PateoId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("PATEO_ID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("STATUS");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TELEFONE");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Telefone")
                        .IsUnique();

                    b.ToTable("FUNCIONARIOS_SYNC");
                });

            modelBuilder.Entity("Csharp.Api.Entities.Moto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("DataCriacaoRegistro")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("DataEntradaPatio")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("DataRecolhimento")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("FuncionarioRecolhimentoId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("Placa")
                        .HasMaxLength(8)
                        .HasColumnType("NVARCHAR2(8)");

                    b.Property<string>("StatusMoto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<Guid>("TagBleId")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime?>("UltimaVezVistoEmPatio")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("UltimoBeaconConhecidoId")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.HasIndex("TagBleId")
                        .IsUnique();

                    b.ToTable("Motos");
                });

            modelBuilder.Entity("Csharp.Api.Entities.TagBle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("CodigoUnicoTag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<int>("NivelBateria")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoUnicoTag")
                        .IsUnique();

                    b.ToTable("TagsBle");
                });

            modelBuilder.Entity("Csharp.Api.Entities.Moto", b =>
                {
                    b.HasOne("Csharp.Api.Entities.TagBle", "Tag")
                        .WithOne("Moto")
                        .HasForeignKey("Csharp.Api.Entities.Moto", "TagBleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Csharp.Api.Entities.TagBle", b =>
                {
                    b.Navigation("Moto")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
